Repository boostcampwm-2022/android10-PlzStop, pull requests merged in 2022-11, with the labels that each got.

#30 [PR] 장소 검색 서치 구현
  build.gradle
  data/build.gradle
  data/src/main/java/com/stop/data/di/NetworkModule.kt
  data/src/main/java/com/stop/data/di/RemoteDataModule.kt
  data/src/main/java/com/stop/data/di/RepositoryModule.kt
  data/src/main/java/com/stop/data/model/nearplace/Place.kt
  data/src/main/java/com/stop/data/model/nearplace/RoadAddress.kt
  data/src/main/java/com/stop/data/remote/ResponseAdapter.kt
  data/src/main/java/com/stop/data/remote/ResponseAdapterFactory.kt
  data/src/main/java/com/stop/data/remote/ResponseCall.kt
  data/src/main/java/com/stop/data/remote/model/Error.kt
  data/src/main/java/com/stop/data/remote/model/ErrorResponse.kt
  data/src/main/java/com/stop/data/remote/model/NetworkResult.kt
  data/src/main/java/com/stop/data/remote/model/nearplace/EvChargers.kt
  data/src/main/java/com/stop/data/remote/model/nearplace/NearPlcaeResponse.kt
  data/src/main/java/com/stop/data/remote/model/nearplace/NewAddres.kt
  data/src/main/java/com/stop/data/remote/model/nearplace/NewAddressList.kt
  data/src/main/java/com/stop/data/remote/model/nearplace/Poi.kt
  data/src/main/java/com/stop/data/remote/model/nearplace/Pois.kt
  data/src/main/java/com/stop/data/remote/model/nearplace/SearchPoiInfo.kt
  data/src/main/java/com/stop/data/remote/network/NearPlaceApiService.kt
  data/src/main/java/com/stop/data/remote/source/nearplace/NearPlaceRemoteDataSource.kt
  data/src/main/java/com/stop/data/remote/source/nearplace/NearPlaceRemoteDataSourceImpl.kt
  data/src/main/java/com/stop/data/repository/NearPlaceRepositoryImpl.kt
  domain/build.gradle
  domain/src/main/java/com/stop/domain/di/UseCaseModule.kt
  domain/src/main/java/com/stop/domain/model/nearplace/Place.kt
  domain/src/main/java/com/stop/domain/model/nearplace/RoadAddress.kt
  domain/src/main/java/com/stop/domain/repository/NearPlaceRepository.kt
  domain/src/main/java/com/stop/domain/usecase/nearplace/GetNearPlacesUseCase.kt
  domain/src/main/java/com/stop/domain/usecase/nearplace/GetNearPlacesUseCaseImpl.kt
  gradle.properties
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/stop/MainActivity.kt
  presentation/src/main/java/com/stop/TroubleShooterApplication.kt
  presentation/src/main/java/com/stop/bindingadapter/RecyclerViewBindingAdapter.kt
  presentation/src/main/java/com/stop/bindingadapter/TextViewBindingAdapter.kt
  presentation/src/main/java/com/stop/ui/nearplace/NearPlaceAdapter.kt
  presentation/src/main/java/com/stop/ui/nearplace/PlaceSearchFragment.kt
  presentation/src/main/java/com/stop/ui/nearplace/PlaceSearchViewModel.kt
  presentation/src/main/res/drawable/background_gray_d9_16.xml
  presentation/src/main/res/drawable/background_gray_d9_8.xml
  presentation/src/main/res/drawable/ic_baseline_location_searching_16.xml
  presentation/src/main/res/drawable/ic_baseline_map_16.xml
  presentation/src/main/res/drawable/ic_baseline_search_24.xml
  presentation/src/main/res/drawable/ic_baseline_star_outline_16.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_place_search.xml
  presentation/src/main/res/layout/item_near_place.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청

#31 [PR] User 위치 동기화 및 드래그 이벤트 구현
  presentation/build.gradle
  presentation/src/main/java/com/stop/MainActivity.kt
  presentation/src/main/java/com/stop/bindingadapter/RecyclerViewBindingAdapter.kt
  presentation/src/main/java/com/stop/ui/map/MapFragment.kt
  presentation/src/main/java/com/stop/ui/nearplace/NearPlaceAdapter.kt
  presentation/src/main/java/com/stop/ui/nearplace/PlaceSearchFragment.kt
  presentation/src/main/java/com/stop/ui/nearplace/PlaceSearchViewModel.kt
  presentation/src/main/res/drawable/ic_bookmark.xml
  presentation/src/main/res/layout/fragment_map.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청

#38 [PR] Sprint2 Sync 작업
  presentation/src/main/java/com/stop/MainActivity.kt
  presentation/src/main/java/com/stop/ui/map/MapFragment.kt
  presentation/src/main/java/com/stop/ui/nearplace/PlaceSearchFragment.kt
  presentation/src/main/java/com/stop/ui/nearplace/PlaceSearchViewModel.kt
  presentation/src/main/res/navigation/plz_stop_navigation.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰완료

#43 [PR] 지도에 북마크 표시 구현, panel 구현시 dataBinding으로 변경
  data/src/main/java/com/stop/data/di/RemoteDataModule.kt
  data/src/main/java/com/stop/data/remote/model/nearplace/NearPlaceResponse.kt
  data/src/main/java/com/stop/data/remote/network/FakeTmapApiService.kt
  data/src/main/java/com/stop/data/remote/network/NearPlaceApiService.kt
  data/src/main/java/com/stop/data/remote/source/route/RouteRemoteDataSource.kt
  data/src/main/java/com/stop/data/remote/source/route/RouteRemoteDataSourceImpl.kt
  data/src/main/java/com/stop/data/repository/RouteRepositoryImpl.kt
  domain/src/main/java/com/stop/domain/di/UseCaseModule.kt
  domain/src/main/java/com/stop/domain/model/geoLocation/AddressType.kt
  domain/src/main/java/com/stop/domain/model/geoLocation/GeoLocationInfo.kt
  domain/src/main/java/com/stop/domain/model/route/tmap/origin/AddressInfo.kt
  domain/src/main/java/com/stop/domain/repository/RouteRepository.kt
  domain/src/main/java/com/stop/domain/usecase/GetRouteUseCaseImpl.kt
  domain/src/main/java/com/stop/domain/usecase/geoLocation/GeoLocationUseCase.kt
  domain/src/main/java/com/stop/domain/usecase/geoLocation/GeoLocationUseCaseImpl.kt
  domain/src/main/java/com/stop/domain/usecase/route/GetRouteUseCase.kt
  presentation/src/main/java/com/stop/ui/map/MapFragment.kt
  presentation/src/main/java/com/stop/ui/placesearch/PlaceSearchViewModel.kt
  presentation/src/main/java/com/stop/ui/route/RouteViewModel.kt
  presentation/src/main/res/drawable/ic_baseline_stars_32.xml
  presentation/src/main/res/layout/fragment_map.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청

#46 [알람 화면] 알람 database 구축
  data/build.gradle
  data/src/main/java/com/stop/data/di/DataSourceModule.kt
  data/src/main/java/com/stop/data/di/DatabaseModule.kt
  data/src/main/java/com/stop/data/di/RemoteDataModule.kt
  data/src/main/java/com/stop/data/di/RepositoryModule.kt
  data/src/main/java/com/stop/data/local/database/dao/AlarmDao.kt
  data/src/main/java/com/stop/data/local/database/dao/TroubleShooterApplicationDatabase.kt
  data/src/main/java/com/stop/data/local/entity/AlarmEntity.kt
  data/src/main/java/com/stop/data/local/source/alarm/AlarmLocalDataSource.kt
  data/src/main/java/com/stop/data/local/source/alarm/AlarmLocalDataSourceImpl.kt
  data/src/main/java/com/stop/data/model/alarm/AlarmRepositoryItem.kt
  data/src/main/java/com/stop/data/repository/AlarmRepositoryImpl.kt
  domain/src/main/java/com/stop/domain/di/UseCaseModule.kt
  domain/src/main/java/com/stop/domain/model/alarm/AlarmUseCaseItem.kt
  domain/src/main/java/com/stop/domain/repository/AlarmRepository.kt
  domain/src/main/java/com/stop/domain/usecase/alarm/DeleteAlarmUseCase.kt
  domain/src/main/java/com/stop/domain/usecase/alarm/DeleteAlarmUseCaseImpl.kt
  domain/src/main/java/com/stop/domain/usecase/alarm/GetAlarmUseCase.kt
  domain/src/main/java/com/stop/domain/usecase/alarm/GetAlarmUseCaseImpl.kt
  domain/src/main/java/com/stop/domain/usecase/alarm/InsertAlarmUseCase.kt
  domain/src/main/java/com/stop/domain/usecase/alarm/InsertAlarmUseCaseImpl.kt
  domain/src/main/java/com/stop/domain/usecase/route/GetRouteUseCaseImpl.kt
  presentation/src/main/res/layout/fragment_alarm_start.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청

#44 [PR] 알람 설정 화면 뷰 구현
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingFragment.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingViewModel.kt
  presentation/src/main/java/com/stop/ui/placesearch/PlaceSearchFragment.kt
  presentation/src/main/res/drawable/ic_baseline_directions_walk_32.xml
  presentation/src/main/res/drawable/ic_baseline_keyboard_arrow_down_24.xml
  presentation/src/main/res/drawable/ic_baseline_keyboard_arrow_up_24.xml
  presentation/src/main/res/layout/fragment_alarm_setting.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 리뷰요청

#48 [PR] 멘토님 리뷰 받은 부분 수정
  data/src/main/java/com/stop/data/di/DataSourceModule.kt
  data/src/main/java/com/stop/data/di/RepositoryModule.kt
  data/src/main/java/com/stop/data/remote/source/nearplace/NearPlaceRemoteDataSource.kt
  data/src/main/java/com/stop/data/remote/source/nearplace/NearPlaceRemoteDataSourceImpl.kt
  data/src/main/java/com/stop/data/repository/NearPlaceRepositoryImpl.kt
  domain/src/main/java/com/stop/domain/repository/NearPlaceRepository.kt
  domain/src/main/java/com/stop/domain/usecase/nearplace/GetNearPlacesUseCase.kt
  domain/src/main/java/com/stop/domain/usecase/nearplace/GetNearPlacesUseCaseImpl.kt
  presentation/src/main/java/com/stop/ui/map/MapFragment.kt
  presentation/src/main/java/com/stop/ui/placesearch/NearPlaceAdapter.kt
  presentation/src/main/java/com/stop/ui/placesearch/PlaceSearchFragment.kt
  presentation/src/main/java/com/stop/ui/placesearch/PlaceSearchViewModel.kt
Labels: 리뷰요청

#49 [PR] Room을 이용한 알람정보 저장 -> DataStore를 이용한 알람정보 저장으로 변경
  data/build.gradle
  data/src/main/java/com/stop/data/di/DataSourceModule.kt
  data/src/main/java/com/stop/data/di/DatabaseModule.kt
  data/src/main/java/com/stop/data/di/LocalDataSourceModule.kt
  data/src/main/java/com/stop/data/local/database/dao/AlarmDao.kt
  data/src/main/java/com/stop/data/local/database/dao/TroubleShooterApplicationDatabase.kt
  data/src/main/java/com/stop/data/local/entity/AlarmEntity.kt
  data/src/main/java/com/stop/data/local/model/Alarm.kt
  data/src/main/java/com/stop/data/local/source/alarm/AlarmLocalDataSource.kt
  data/src/main/java/com/stop/data/local/source/alarm/AlarmLocalDataSourceImpl.kt
  data/src/main/java/com/stop/data/model/alarm/AlarmRepositoryItem.kt
  data/src/main/java/com/stop/data/repository/AlarmRepositoryImpl.kt
  domain/src/main/java/com/stop/domain/di/UseCaseModule.kt
  domain/src/main/java/com/stop/domain/model/alarm/AlarmUseCaseItem.kt
  domain/src/main/java/com/stop/domain/repository/AlarmRepository.kt
  domain/src/main/java/com/stop/domain/usecase/alarm/DeleteAlarmUseCase.kt
  domain/src/main/java/com/stop/domain/usecase/alarm/DeleteAlarmUseCaseImpl.kt
  domain/src/main/java/com/stop/domain/usecase/alarm/GetAlarmUseCase.kt
  domain/src/main/java/com/stop/domain/usecase/alarm/GetAlarmUseCaseImpl.kt
  domain/src/main/java/com/stop/domain/usecase/alarm/SaveAlarmUseCase.kt
  domain/src/main/java/com/stop/domain/usecase/alarm/SaveAlarmUseCaseImpl.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingFragment.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingViewModel.kt
  presentation/src/main/res/navigation/nav_graph.xml
Labels: 리뷰요청

#47 지도에 사용자의 이동경로 그리기, 이동경로를 흉내내는 코드 만들기
  presentation/src/main/java/com/stop/ui/mission/MissionFragment.kt
  presentation/src/main/java/com/stop/ui/mission/MissionViewModel.kt
  presentation/src/main/java/com/stop/ui/mission/TMap.kt
  presentation/src/main/java/com/stop/ui/mission/TMapHandler.kt
  presentation/src/main/res/drawable/ic_baseline_cancel_24.xml
  presentation/src/main/res/layout/fragment_mission.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청

#50 [PR] map의 공통 로직 TMap class 구현 및 버스 실시간 bus line 그리기
  data/src/main/java/com/stop/data/di/DataSourceModule.kt
  data/src/main/java/com/stop/data/di/RepositoryModule.kt
  data/src/main/java/com/stop/data/model/nowlocation/BusInfoRepositoryItem.kt
  data/src/main/java/com/stop/data/remote/model/nowlocation/BusBody.kt
  data/src/main/java/com/stop/data/remote/model/nowlocation/BusInfo.kt
  data/src/main/java/com/stop/data/remote/model/nowlocation/GetBusNowLocationResponse.kt
  data/src/main/java/com/stop/data/remote/network/WsBusApiService.kt
  data/src/main/java/com/stop/data/remote/source/nowlocation/NowLocationRemoteDataSource.kt
  data/src/main/java/com/stop/data/remote/source/nowlocation/NowLocationRemoteDataSourceImpl.kt
  data/src/main/java/com/stop/data/repository/NowLocationRepositoryImpl.kt
  domain/src/main/java/com/stop/domain/di/UseCaseModule.kt
  domain/src/main/java/com/stop/domain/model/nowlocation/BusInfoUseCaseItem.kt
  domain/src/main/java/com/stop/domain/repository/NowLocationRepository.kt
  domain/src/main/java/com/stop/domain/usecase/nowlocation/GetBusNowLocationUseCase.kt
  domain/src/main/java/com/stop/domain/usecase/nowlocation/GetBusNowLocationUseCaseImpl.kt
  presentation/src/main/java/com/stop/ui/map/MapFragment.kt
  presentation/src/main/java/com/stop/ui/map/MapHandler.kt
  presentation/src/main/java/com/stop/ui/map/MapTMap.kt
  presentation/src/main/java/com/stop/ui/mission/MissionFragment.kt
  presentation/src/main/java/com/stop/ui/mission/MissionHandler.kt
  presentation/src/main/java/com/stop/ui/mission/MissionTMap.kt
  presentation/src/main/java/com/stop/ui/mission/MissionViewModel.kt
  presentation/src/main/java/com/stop/ui/mission/TMapHandler.kt
  presentation/src/main/java/com/stop/ui/util/Handler.kt
  presentation/src/main/java/com/stop/ui/util/TMap.kt
  presentation/src/main/res/drawable/ic_baseline_directions_bus_32.xml
  presentation/src/main/res/drawable/ic_baseline_directions_bus_big.xml
  presentation/src/main/res/layout/fragment_map.xml
  presentation/src/main/res/layout/fragment_mission.xml
  presentation/src/main/res/layout/view_marker2.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청

#53 [PR] Workmanager를 주기적 백그라운드 네트워크 요청
  data/src/main/java/com/stop/data/local/source/alarm/AlarmLocalDataSourceImpl.kt
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/stop/AlarmWorker.kt
  presentation/src/main/java/com/stop/TroubleShooterApplication.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingFragment.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingViewModel.kt
  presentation/src/main/res/layout/fragment_alarm_setting.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/themes.xml
Labels: 리뷰요청, feat
