Repository boostcampwm-2022/android10-PlzStop, pull requests merged in 2022-12, with the labels that each got.

#56 [PR] Splash Screen 구현
  presentation/build.gradle
  presentation/src/debug/ic_bus-playstore.png
  presentation/src/debug/res/mipmap-anydpi-v26/ic_bus.xml
  presentation/src/debug/res/mipmap-anydpi-v26/ic_bus_round.xml
  presentation/src/debug/res/mipmap-hdpi/ic_bus.png
  presentation/src/debug/res/mipmap-hdpi/ic_bus_foreground.png
  presentation/src/debug/res/mipmap-hdpi/ic_bus_round.png
  presentation/src/debug/res/mipmap-mdpi/ic_bus.png
  presentation/src/debug/res/mipmap-mdpi/ic_bus_foreground.png
  presentation/src/debug/res/mipmap-mdpi/ic_bus_round.png
  presentation/src/debug/res/mipmap-xhdpi/ic_bus.png
  presentation/src/debug/res/mipmap-xhdpi/ic_bus_foreground.png
  presentation/src/debug/res/mipmap-xhdpi/ic_bus_round.png
  presentation/src/debug/res/mipmap-xxhdpi/ic_bus.png
  presentation/src/debug/res/mipmap-xxhdpi/ic_bus_foreground.png
  presentation/src/debug/res/mipmap-xxhdpi/ic_bus_round.png
  presentation/src/debug/res/mipmap-xxxhdpi/ic_bus.png
  presentation/src/debug/res/mipmap-xxxhdpi/ic_bus_foreground.png
  presentation/src/debug/res/mipmap-xxxhdpi/ic_bus_round.png
  presentation/src/debug/res/values/ic_bus_background.xml
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/stop/AlarmWorker.kt
  presentation/src/main/java/com/stop/MainActivity.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmViewModel.kt
  presentation/src/main/java/com/stop/ui/map/MapFragment.kt
  presentation/src/main/java/com/stop/ui/map/MapTMap.kt
  presentation/src/main/java/com/stop/ui/mission/MissionFragment.kt
  presentation/src/main/java/com/stop/ui/mission/MissionTMap.kt
  presentation/src/main/java/com/stop/ui/util/TMap.kt
  presentation/src/main/res/drawable/avd_splash.xml
  presentation/src/main/res/drawable/ic_place_marker.xml
  presentation/src/main/res/drawable/vd_branding.xml
  presentation/src/main/res/layout/fragment_map.xml
  presentation/src/main/res/layout/home_bottom_sheet.xml
  presentation/src/main/res/layout/home_panel.xml
  presentation/src/main/res/values-v31/themes.xml
  presentation/src/main/res/values/themes.xml
Labels: 리뷰요청

#57 지하철 막차 시간 구하기, 경기도 버스 막차 시간 구하기
  data/src/main/java/com/stop/data/remote/model/route/gyeonggi/GetGyeonggiBusStationIdResponse.kt
  data/src/main/java/com/stop/data/remote/model/route/gyeonggi/GyeonggiBusLastTime.kt
  data/src/main/java/com/stop/data/remote/model/route/gyeonggi/GyeonggiBusLastTimeResponse.kt
  data/src/main/java/com/stop/data/remote/model/route/gyeonggi/GyeonggiBusRoute.kt
  data/src/main/java/com/stop/data/remote/model/route/gyeonggi/GyeonggiBusRouteIdResponse.kt
  data/src/main/java/com/stop/data/remote/model/route/gyeonggi/GyeonggiBusRouteStationsResponse.kt
  data/src/main/java/com/stop/data/remote/model/route/gyeonggi/GyeonggiBusStation.kt
  data/src/main/java/com/stop/data/remote/model/route/gyeonggi/GyeonggiBusStationIdResponse.kt
  data/src/main/java/com/stop/data/remote/model/route/gyeonggi/MsgBody.kt
  data/src/main/java/com/stop/data/remote/network/ApisDataService.kt
  data/src/main/java/com/stop/data/remote/network/OpenApiSeoulService.kt
  data/src/main/java/com/stop/data/remote/network/WsBusApiService.kt
  data/src/main/java/com/stop/data/remote/source/route/RouteRemoteDataSource.kt
  data/src/main/java/com/stop/data/remote/source/route/RouteRemoteDataSourceImpl.kt
  data/src/main/java/com/stop/data/repository/RouteRepositoryImpl.kt
  domain/src/main/java/com/stop/domain/model/route/TransportIdRequest.kt
  domain/src/main/java/com/stop/domain/model/route/gyeonggi/GetGyeonggiBusStationIdResponse.kt
  domain/src/main/java/com/stop/domain/model/route/gyeonggi/GyeonggiBusLastTime.kt
  domain/src/main/java/com/stop/domain/model/route/gyeonggi/GyeonggiBusRoute.kt
  domain/src/main/java/com/stop/domain/model/route/gyeonggi/MsgBody.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/bus/BusLastTimeResponse.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/bus/BusRouteInfo.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/bus/BusRouteResponse.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/bus/BusStationArsIdResponse.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/bus/LastTimeInfo.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/bus/RouteIdMsgBody.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/subway/SearchLastTrainTimeByIDService.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/subway/SearchStationNameBySubwayLineInfo.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/subway/Station.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/subway/StationLastTime.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/subway/SubwayCircleType.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/subway/SubwayLastTimeResponse.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/subway/SubwayStationsResponse.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/subway/WeekType.kt
  domain/src/main/java/com/stop/domain/repository/RouteRepository.kt
  domain/src/main/java/com/stop/domain/usecase/route/GetLastTransportTimeUseCase.kt
  domain/src/main/java/com/stop/domain/usecase/route/GetLastTransportTimeUseCaseImpl.kt
  domain/src/main/java/com/stop/domain/usecase/route/GetRouteUseCase.kt
  domain/src/main/java/com/stop/domain/usecase/route/GetRouteUseCaseImpl.kt
  presentation/src/main/java/com/stop/model/route/MoveType.kt
  presentation/src/main/java/com/stop/model/route/OrderType.kt
  presentation/src/main/java/com/stop/model/route/RouteRequest.kt
  presentation/src/main/java/com/stop/model/route/RouteResponse.kt
  presentation/src/main/java/com/stop/model/route/Station.kt
  presentation/src/main/java/com/stop/model/route/SubRoute.kt
  presentation/src/main/java/com/stop/model/route/TransportSubRoute.kt
  presentation/src/main/java/com/stop/model/route/WalkInfo.kt
  presentation/src/main/java/com/stop/model/route/WalkSubRoute.kt
  presentation/src/main/java/com/stop/ui/route/OnItineraryClickListener.kt
  presentation/src/main/java/com/stop/ui/route/RouteAdapter.kt
  presentation/src/main/java/com/stop/ui/route/RouteFragment.kt
  presentation/src/main/java/com/stop/ui/route/RouteViewHolder.kt
  presentation/src/main/java/com/stop/ui/route/RouteViewModel.kt
  presentation/src/main/java/com/stop/ui/routedetail/RouteDetailFragment.kt
  presentation/src/main/res/layout/fragment_route_detail.xml
  presentation/src/main/res/navigation/nav_graph.xml
Labels: 리뷰요청

#59 [PR] 임의의 값으로 알람 구현완료
  data/src/main/java/com/stop/data/local/model/Alarm.kt
  data/src/main/java/com/stop/data/model/alarm/AlarmRepositoryItem.kt
  data/src/main/java/com/stop/data/repository/AlarmRepositoryImpl.kt
  domain/src/main/java/com/stop/domain/model/alarm/AlarmUseCaseItem.kt
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/stop/AlarmFunctions.kt
  presentation/src/main/java/com/stop/AlarmReceiver.kt
  presentation/src/main/java/com/stop/AlarmWorker.kt
  presentation/src/main/java/com/stop/BuildVersion.kt
  presentation/src/main/java/com/stop/SoundService.kt
  presentation/src/main/java/com/stop/TestActivity.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingFragment.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingViewModel.kt
  presentation/src/main/res/drawable/ic_baseline_alarm_on_24.xml
  presentation/src/main/res/layout/activity_test.xml
  presentation/src/main/res/navigation/nav_graph.xml
Labels: 리뷰요청

#62 버스 막차 계산 로직 관련 오류 수정, LiveData 중복 observe 문제 처리
  data/src/main/java/com/stop/data/remote/model/route/gyeonggi/GyeonggiBusLastTimeResponse.kt
  data/src/main/java/com/stop/data/remote/source/route/RouteRemoteDataSource.kt
  data/src/main/java/com/stop/data/remote/source/route/RouteRemoteDataSourceImpl.kt
  data/src/main/java/com/stop/data/repository/RouteRepositoryImpl.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/bus/LastTimeMsgBody.kt
  domain/src/main/java/com/stop/domain/repository/RouteRepository.kt
  domain/src/main/java/com/stop/domain/usecase/route/GetLastTransportTimeUseCaseImpl.kt
  presentation/src/main/java/com/stop/ui/route/RouteFragment.kt
  presentation/src/main/java/com/stop/ui/route/RouteViewModel.kt
  presentation/src/main/res/navigation/nav_graph.xml
Labels: bug

#64 [PR] 모든 화면 연결 작업 완료
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/stop/AlarmFunctions.kt
  presentation/src/main/java/com/stop/AlarmReceiver.kt
  presentation/src/main/java/com/stop/MainActivity.kt
  presentation/src/main/java/com/stop/SoundService.kt
  presentation/src/main/java/com/stop/TestActivity.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingFragment.kt
  presentation/src/main/java/com/stop/ui/alarmstart/AlarmStartFragment.kt
  presentation/src/main/java/com/stop/ui/map/MapTMap.kt
  presentation/src/main/java/com/stop/ui/routedetail/RouteDetailFragment.kt
  presentation/src/main/res/layout/activity_test.xml
  presentation/src/main/res/layout/fragment_alarm_setting.xml
  presentation/src/main/res/layout/fragment_place_search.xml
Labels: 리뷰요청

#68 [PR] 백그라운드 알람 갱신 작업
  presentation/src/main/java/com/stop/AlarmFunctions.kt
  presentation/src/main/java/com/stop/AlarmReceiver.kt
  presentation/src/main/java/com/stop/AlarmWorker.kt
  presentation/src/main/java/com/stop/BuildVersionCheck.kt
  presentation/src/main/java/com/stop/LastTimeCheckWorker.kt
  presentation/src/main/java/com/stop/TimeConverter.kt
  presentation/src/main/java/com/stop/di/AlarmModule.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingFragment.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingViewModel.kt
  presentation/src/main/java/com/stop/ui/alarmstart/AlarmStartFragment.kt
  presentation/src/main/java/com/stop/ui/route/ClickRouteViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청

#72 Navigation Component 작업
  domain/src/main/java/com/stop/domain/model/route/tmap/custom/Route.kt
  domain/src/main/java/com/stop/domain/model/route/tmap/custom/TransportRoute.kt
  domain/src/main/java/com/stop/domain/model/route/tmap/custom/WalkRoute.kt
  domain/src/main/java/com/stop/domain/usecase/route/GetRouteUseCaseImpl.kt
  presentation/src/main/java/com/stop/MainActivity.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingFragment.kt
  presentation/src/main/java/com/stop/ui/bookmark/BookMarkFragment.kt
  presentation/src/main/java/com/stop/ui/map/MapFragment.kt
  presentation/src/main/java/com/stop/ui/placesearch/PlaceSearchFragment.kt
  presentation/src/main/java/com/stop/ui/route/ClickRouteViewModel.kt
  presentation/src/main/java/com/stop/ui/route/RouteFragment.kt
  presentation/src/main/java/com/stop/ui/route/RouteResultViewModel.kt
  presentation/src/main/java/com/stop/ui/route/RouteViewHolder.kt
  presentation/src/main/java/com/stop/ui/route/RouteViewModel.kt
  presentation/src/main/java/com/stop/ui/route/TimeLineAdapter.kt
  presentation/src/main/java/com/stop/ui/route/TimeLineViewHolder.kt
  presentation/src/main/java/com/stop/ui/routedetail/RouteDetailFragment.kt
  presentation/src/main/res/layout/fragment_book_mark.xml
  presentation/src/main/res/layout/fragment_route_detail.xml
  presentation/src/main/res/layout/route_item.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/navigation/route_nav_graph.xml
  presentation/src/main/res/values/colors.xml
Labels: feat

#73 [PR] 버그 픽스 및 장소 검색 UI 수정
  data/src/main/java/com/stop/data/local/model/RecentPlaceSearchEntity.kt
  data/src/main/java/com/stop/data/remote/model/nearplace/Poi.kt
  presentation/src/main/java/com/stop/MainActivity.kt
  presentation/src/main/java/com/stop/TopBottomPadding.kt
  presentation/src/main/java/com/stop/bindingadapter/EditTextBindingAdapter.kt
  presentation/src/main/java/com/stop/ui/map/MapFragment.kt
  presentation/src/main/java/com/stop/ui/placesearch/PlaceSearchFragment.kt
  presentation/src/main/java/com/stop/ui/placesearch/PlaceSearchViewModel.kt
  presentation/src/main/res/drawable/ic_baseline_search_24.xml
  presentation/src/main/res/drawable/icon_error.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/dialog_progress.xml
  presentation/src/main/res/layout/fragment_map.xml
  presentation/src/main/res/layout/fragment_place_search.xml
  presentation/src/main/res/layout/item_near_place.xml
  presentation/src/main/res/layout/item_recent_search.xml
  presentation/src/main/res/layout/layout_recent_search.xml
  presentation/src/main/res/values-v31/themes.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/styles.xml
  presentation/src/main/res/values/themes.xml
Labels: 리뷰요청

#79 정류소 이름 전처리 로직 변경, API 요청 데이터가 없을 때 대응처리
  data/src/main/java/com/stop/data/di/ApiModule.kt
  data/src/main/java/com/stop/data/remote/model/nowlocation/bus/BusBody.kt
  data/src/main/java/com/stop/data/remote/model/nowlocation/subway/SubwayTrainNowLocationResponse.kt
  data/src/main/java/com/stop/data/remote/model/route/gyeonggi/GyeonggiBusLastTimeResponse.kt
  data/src/main/java/com/stop/data/remote/network/FakeTmapApiService.kt
  data/src/main/java/com/stop/data/remote/source/nowlocation/NowLocationRemoteDataSourceImpl.kt
  data/src/main/java/com/stop/data/remote/source/route/RouteRemoteDataSource.kt
  data/src/main/java/com/stop/data/remote/source/route/RouteRemoteDataSourceImpl.kt
  data/src/main/java/com/stop/data/repository/RouteRepositoryImpl.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/bus/ArsIdMsgBody.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/bus/RouteIdMsgBody.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/subway/SubwayLastTimeResponse.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/subway/SubwayStationResponse.kt
  domain/src/main/java/com/stop/domain/model/route/seoul/subway/SubwayStationsResponse.kt
  domain/src/main/java/com/stop/domain/repository/RouteRepository.kt
  domain/src/main/java/com/stop/domain/usecase/route/GetLastTransportTimeUseCaseImpl.kt
  domain/src/main/java/com/stop/domain/usecase/route/GetRouteUseCaseImpl.kt
  presentation/src/main/java/com/stop/ui/placesearch/PlaceSearchViewModel.kt
Labels: bug

#82 [PR] 미션 종료 구현 & bottom_sheet ui 디자인 수정
  presentation/src/main/assets/bus_animation.json
  presentation/src/main/assets/fail_animation.json
  presentation/src/main/assets/success_animation.json
  presentation/src/main/java/com/stop/MainActivity.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingViewModel.kt
  presentation/src/main/java/com/stop/ui/map/MapFragment.kt
  presentation/src/main/java/com/stop/ui/mission/MissionFragment.kt
  presentation/src/main/java/com/stop/ui/mission/MissionManager.kt
  presentation/src/main/java/com/stop/ui/mission/MissionTMap.kt
  presentation/src/main/java/com/stop/ui/mission/MissionViewModel.kt
  presentation/src/main/java/com/stop/ui/mission/MissionWorker.kt
  presentation/src/main/java/com/stop/ui/util/TMap.kt
  presentation/src/main/res/drawable/ic_alarm_white.xml
  presentation/src/main/res/drawable/selected_mission_button.xml
  presentation/src/main/res/drawable/unselected_mission_button.xml
  presentation/src/main/res/layout/bottom_sheet_home_state_expanded.xml
  presentation/src/main/res/layout/fragment_mission.xml
  presentation/src/main/res/layout/route_path_item.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청

#83 [PR] 알람 일부 버그수정 ㅠㅠ
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/stop/AlarmFunctions.kt
  presentation/src/main/java/com/stop/AlarmReceiver.kt
  presentation/src/main/java/com/stop/MainActivity.kt
  presentation/src/main/java/com/stop/alarm/AlarmFunctions.kt
  presentation/src/main/java/com/stop/alarm/AlarmReceiver.kt
  presentation/src/main/java/com/stop/alarm/LastTimeCheckWorker.kt
  presentation/src/main/java/com/stop/alarm/SoundService.kt
  presentation/src/main/java/com/stop/di/AlarmModule.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingFragment.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingViewModel.kt
  presentation/src/main/java/com/stop/ui/alarmstart/AlarmStartFragment.kt
  presentation/src/main/java/com/stop/ui/map/MapFragment.kt
  presentation/src/main/java/com/stop/ui/placesearch/PlaceSearchFragment.kt
  presentation/src/main/java/com/stop/util/BuildVersionCheck.kt
  presentation/src/main/java/com/stop/util/Context.kt
  presentation/src/main/java/com/stop/util/TimeConverter.kt
  presentation/src/main/java/com/stop/util/TopBottomPadding.kt
  presentation/src/main/res/layout/fragment_map.xml
  presentation/src/main/res/values/strings.xml
Labels: bug

#90 [PR] 지난 pr bug 해결 - bottom_sheet 에러 해결, 초기 위치 추가
  presentation/src/main/java/com/stop/ui/mission/MissionFragment.kt
  presentation/src/main/java/com/stop/ui/mission/MissionTMap.kt
  presentation/src/main/java/com/stop/ui/mission/MissionWorker.kt
  presentation/src/main/java/com/stop/ui/util/Marker.kt
  presentation/src/main/res/drawable-v24/ic_person_marker.xml
  presentation/src/main/res/layout/bottom_sheet_home_state_expanded.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: bug

#100 [PR] 미션 Foreground Service로 마이그레이션
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/assets/fail_animation2.json
  presentation/src/main/java/com/stop/alarm/AlarmReceiver.kt
  presentation/src/main/java/com/stop/di/MissionModule.kt
  presentation/src/main/java/com/stop/model/AlarmStatus.kt
  presentation/src/main/java/com/stop/model/Location.kt
  presentation/src/main/java/com/stop/model/MissionStatus.kt
  presentation/src/main/java/com/stop/ui/alarmsetting/AlarmSettingViewModel.kt
  presentation/src/main/java/com/stop/ui/alarmstart/AlarmStartFragment.kt
  presentation/src/main/java/com/stop/ui/map/MapFragment.kt
  presentation/src/main/java/com/stop/ui/mission/MissionFragment.kt
  presentation/src/main/java/com/stop/ui/mission/MissionService.kt
  presentation/src/main/java/com/stop/ui/mission/MissionTMap.kt
  presentation/src/main/java/com/stop/ui/mission/MissionViewModel.kt
  presentation/src/main/java/com/stop/ui/mission/MissionWorker.kt
  presentation/src/main/java/com/stop/ui/util/TMap.kt
  presentation/src/main/res/layout/bottom_sheet_home_state_expanded.xml
  presentation/src/main/res/layout/fragment_map.xml
  presentation/src/main/res/layout/fragment_mission.xml
  presentation/src/main/res/layout/home_bottom_sheet.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: feat

#104 [PR] 미션 이슈 해결
  presentation/src/main/java/com/stop/ui/mission/MissionFragment.kt
  presentation/src/main/java/com/stop/ui/mission/MissionService.kt
  presentation/src/main/java/com/stop/ui/mission/MissionTMap.kt
Labels: bug
